version: '3.4'

services:
  mysql_service_nane:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=nanerootpass
      - MYSQL_DATABASE=nanedb
      - MYSQL_USER=naneuser
      - MYSQL_PASSWORD=nanepass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

volumes:
  mysql_data:
    driver: local